services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: amo-app
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: amo-postgres
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      APP_PORT: ${APP_PORT}
      AMO_WEBHOOK_BASE_URL: ${AMO_WEBHOOK_BASE_URL}
      AMO_CLIENT_ID: ${AMO_CLIENT_ID}
      AMO_CLIENT_SECRET: ${AMO_CLIENT_SECRET}
      AMO_REDIRECT_URI: ${AMO_REDIRECT_URI}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      AMO_ERROR_TASK_TYPE_ID: ${AMO_ERROR_TASK_TYPE_ID}
      AMO_CHECK_TASK_TYPE_ID: ${AMO_CHECK_TASK_TYPE_ID}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: